services:
  git-server:
    build: git-server
    container_name: git-server
    hostname: git-server
    restart: unless-stopped

    ports:
      - 22:22

    volumes:
      - ./git-server/repos:/home/git/repos
    networks:
      - git-isolated-network

  ssh-bridge:
    build: ssh-bridge
    container_name: ssh-bridge
    hostname: ssh-bridge
    restart: unless-stopped

    ports:
      - 22:22

    networks:
      - public
      - git-isolated-network

  password-mgr:
    build: password-mgr
    container_name: password-mgr
    hostname: password-mgr
    restart: unless-stopped

    ports:
      - 8080:8080

    # TODO isolate as well
    #networks:
    #  - public

networks:
  public:
  git-isolated-network:
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.3.0.0/24
          gateway: 172.3.0.254
